title: Oladimeji Adeyemi

logo: my image.jpeg

description: A Data and Business Intelligence Analyst with over two years of experience analysing and transforming complex datasets that support informed decision making and drive business growth. Proficient in data analysis and visualisation tools, including Excel, SQL, and Power BI, with a strong ability to identify trends, generate meaningful insights, and communicate data driven recommendations effectively.

#show_downloads: true

#google_analytics:

theme: jekyll-theme-minimal
